services:
  boldreports:
   image: syncfusion/boldreports
   restart: always
   ports:
     - 8090:80
   networks:
     - boldreports
   volumes:
     - boldreports_data:/application/app_data
    
  pgdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: <Password>                 # Set the password for the PostgreSQL database that will be deployed along with this Bold Reports deployment.
    volumes:
      - db_data:/var/lib/postgresql/data/
    networks:
      - boldreports

networks:
  boldreports:
  
volumes:
  boldreports_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '<host_path_boldreports_data>'        # Set the path for storing the data of the bold reports.
  db_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '<host_path_db_data>'                 # Set the path for the docker PostgreSQL database data to be stored.